name: automate-generation

on:
  # scheduled: every hour at minute 51 (cron uses UTC)
  schedule:
    - cron: '51 * * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-automate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # make sure common libs are installed if not in requirements
          python -m pip install requests gspread google-auth

      - name: Prepare GSHEET service account JSON
        # If you store the raw JSON in the secret GSHEET_SERVICE_ACCOUNT_JSON, write it to env variable for the script.
        # If you stored base64-encoded JSON, also fine; the script accepts both.
        env:
          GSHEET_SERVICE_ACCOUNT_JSON: ${{ secrets.GSHEET_SERVICE_ACCOUNT_JSON }}
        run: |
          echo "Prepared GSHEET env."

      - name: Run automation script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
          SUPABASE_STORAGE_BUCKET: ${{ secrets.SUPABASE_STORAGE_BUCKET }}
          SUPABASE_TABLE_NAME: ${{ secrets.SUPABASE_TABLE_NAME }}
          GSHEET_SERVICE_ACCOUNT_JSON: ${{ secrets.GSHEET_SERVICE_ACCOUNT_JSON }}
          GSHEET_SPREADSHEET_ID: ${{ secrets.GSHEET_SPREADSHEET_ID }}
          GSHEET_SHEET_NAME: ${{ secrets.GSHEET_SHEET_NAME }}
          LOG_LEVEL: INFO
        run: |
          python automateGeneration.py
