name: Fetch TMart Emails and Upload to Supabase

on:
  schedule:
    # Runs at the top of every hour
    - cron: '0 * * * *'
  # Allows you to hit “Run workflow” in the Actions tab
  workflow_dispatch:

jobs:
  fetch_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare credentials
        run: |
          printf '%s' "$GMAIL_CREDENTIALS" > credentials.json
          printf '%s' "$TOKEN_JSON"     > token.json

      - name: Run Gmail fetcher
        run: python gmail_attachment_fetcher.py
